language: scala

jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

scala:
   - 2.12.9

jobs:
  include:
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - stage: multi-jvm-test
      script: sbt ++$TRAVIS_SCALA_VERSION multi-jvm:test
